# Generated by Django 5.2.8 on 2025-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='asesor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asesor / Docente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso / Ciclo'),
        ),
    ]
