# Generated by Django 5.2.8 on 2025-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_proyecto_asesor_proyecto_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='integrantes',
            field=models.TextField(blank=True, help_text='Escribe un nombre por línea', null=True, verbose_name='Resto de Integrantes'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Líder del Proyecto'),
        ),
    ]
